<?xml version="1.0" encoding="utf-8"?><Database Name="db_sistema" Class="SistemaFormDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=db_sistema;Integrated Security=True" SettingsObjectName="sistemadbs.DAL.Properties.Settings" SettingsPropertyName="db_sistemaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="id_categoria" Member="codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desc_categoria" Member="descricao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Categoria_Produto" Member="Produto" ThisKey="codigo" OtherKey="codCategoria" Type="Produto" />
    </Type>
  </Table>
  <Table Name="dbo.tb_produto" Member="Produto">
    <Type Name="Produto">
      <Column Name="id_produto" Member="codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desc_produto" Member="descricao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="valor" Type="System.Decimal" DbType="Decimal(25,2)" CanBeNull="true" />
      <Column Name="id_categoria" Member="codCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Produto_Itens_Venda" Member="Itens_Venda" ThisKey="codigo" OtherKey="Codigo_produto" Type="Itens_Venda" />
      <Association Name="Categoria_Produto" Member="Categoria" ThisKey="codCategoria" OtherKey="codigo" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_venda" Member="Vendas">
    <Type Name="Vendas">
      <Column Name="id_venda" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="valor" Member="Valor_venda" Storage="_valor" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="desconto" Member="Desconto" Storage="_desconto" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="valor_pago" Member="Valor_pago" Storage="_valor_pago" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="id_pessoa" Member="Codigo_Pessoa_Venda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Vendas_Itens_Venda" Member="Itens_Venda" ThisKey="id_venda" OtherKey="Codigo_venda" Type="Itens_Venda" />
      <Association Name="Vendas_tb_contas_receber" Member="Contas_Receber" ThisKey="id_venda" OtherKey="Codigo_venda" Type="Contas_Receber" />
      <Association Name="Pessoas_Vendas" Member="Pessoas" ThisKey="Codigo_Pessoa_Venda" OtherKey="Codigo_pessoa" Type="Pessoas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_pessoa" Member="Pessoas">
    <Type Name="Pessoas">
      <Column Name="id_pessoa" Member="Codigo_pessoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Member="Nome" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="telefone" Member="Telefone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="email" Member="Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Pessoas_Vendas" Member="Vendas" ThisKey="Codigo_pessoa" OtherKey="Codigo_Pessoa_Venda" Type="Vendas" />
    </Type>
  </Table>
  <Table Name="dbo.tb_usuario" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="usuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="senha" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_pessoa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_itens_venda" Member="Itens_Venda">
    <Type Name="Itens_Venda">
      <Column Name="quantidade" Member="Quantidade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_produto" Member="Codigo_produto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_venda" Member="Codigo_venda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="valor" Member="Valor" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_item" Member="Codigo_item" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Produto_Itens_Venda" Member="Produto" ThisKey="Codigo_produto" OtherKey="codigo" Type="Produto" IsForeignKey="true" />
      <Association Name="Vendas_Itens_Venda" Member="Vendas" ThisKey="Codigo_venda" OtherKey="id_venda" Type="Vendas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_status_pagamento" Member="Status_Pagamento">
    <Type Name="Status_Pagamento">
      <Column Name="id_status" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tb_status_pagamento_tb_contas_receber" Member="Contas_Receber" ThisKey="id_status" OtherKey="Codigo_status" Type="Contas_Receber" />
    </Type>
  </Table>
  <Table Name="dbo.tb_contas_receber" Member="Contas_Receber">
    <Type Name="Contas_Receber">
      <Column Name="id_conta" Member="Codigo_conta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="data_compra" Member="Data_compra" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_vencimento" Member="Data_vencimento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_pagamento" Member="Data_pagamento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_venda" Member="Codigo_venda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_status" Member="Codigo_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_status_pagamento_tb_contas_receber" Member="Status_Pagamento" ThisKey="Codigo_status" OtherKey="id_status" Type="Status_Pagamento" IsForeignKey="true" />
      <Association Name="Vendas_tb_contas_receber" Member="Vendas" ThisKey="Codigo_venda" OtherKey="id_venda" Type="Vendas" IsForeignKey="true" />
    </Type>
  </Table>
</Database>