#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemadbs.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_sistema")]
	public partial class SistemaFormDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertVendas(Vendas instance);
    partial void UpdateVendas(Vendas instance);
    partial void DeleteVendas(Vendas instance);
    partial void InsertPessoas(Pessoas instance);
    partial void UpdatePessoas(Pessoas instance);
    partial void DeletePessoas(Pessoas instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertItens_Venda(Itens_Venda instance);
    partial void UpdateItens_Venda(Itens_Venda instance);
    partial void DeleteItens_Venda(Itens_Venda instance);
    partial void InsertStatus_Pagamento(Status_Pagamento instance);
    partial void UpdateStatus_Pagamento(Status_Pagamento instance);
    partial void DeleteStatus_Pagamento(Status_Pagamento instance);
    partial void InsertContas_Receber(Contas_Receber instance);
    partial void UpdateContas_Receber(Contas_Receber instance);
    partial void DeleteContas_Receber(Contas_Receber instance);
    #endregion
		
		public SistemaFormDataContext() : 
				base(global::sistemadbs.DAL.Properties.Settings.Default.db_sistemaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaFormDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaFormDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaFormDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaFormDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categoria> Categoria
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produto
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Vendas> Vendas
		{
			get
			{
				return this.GetTable<Vendas>();
			}
		}
		
		public System.Data.Linq.Table<Pessoas> Pessoas
		{
			get
			{
				return this.GetTable<Pessoas>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Itens_Venda> Itens_Venda
		{
			get
			{
				return this.GetTable<Itens_Venda>();
			}
		}
		
		public System.Data.Linq.Table<Status_Pagamento> Status_Pagamento
		{
			get
			{
				return this.GetTable<Status_Pagamento>();
			}
		}
		
		public System.Data.Linq.Table<Contas_Receber> Contas_Receber
		{
			get
			{
				return this.GetTable<Contas_Receber>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _descricao;
		
		private EntitySet<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public Categoria()
		{
			this._Produto = new EntitySet<Produto>(new Action<Produto>(this.attach_Produto), new Action<Produto>(this.detach_Produto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desc_categoria", Storage="_descricao", DbType="NVarChar(50)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Produto", Storage="_Produto", ThisKey="codigo", OtherKey="codCategoria")]
		public EntitySet<Produto> Produto
		{
			get
			{
				return this._Produto;
			}
			set
			{
				this._Produto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Produto(Produto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Produto(Produto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produto")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _descricao;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<int> _codCategoria;
		
		private EntitySet<Itens_Venda> _Itens_Venda;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void OncodCategoriaChanging(System.Nullable<int> value);
    partial void OncodCategoriaChanged();
    #endregion
		
		public Produto()
		{
			this._Itens_Venda = new EntitySet<Itens_Venda>(new Action<Itens_Venda>(this.attach_Itens_Venda), new Action<Itens_Venda>(this.detach_Itens_Venda));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_produto", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desc_produto", Storage="_descricao", DbType="NVarChar(50)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(25,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_codCategoria", DbType="Int")]
		public System.Nullable<int> codCategoria
		{
			get
			{
				return this._codCategoria;
			}
			set
			{
				if ((this._codCategoria != value))
				{
					this.OncodCategoriaChanging(value);
					this.SendPropertyChanging();
					this._codCategoria = value;
					this.SendPropertyChanged("codCategoria");
					this.OncodCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Itens_Venda", Storage="_Itens_Venda", ThisKey="codigo", OtherKey="Codigo_produto")]
		public EntitySet<Itens_Venda> Itens_Venda
		{
			get
			{
				return this._Itens_Venda;
			}
			set
			{
				this._Itens_Venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Produto", Storage="_Categoria", ThisKey="codCategoria", OtherKey="codigo", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Produto.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Produto.Add(this);
						this._codCategoria = value.codigo;
					}
					else
					{
						this._codCategoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Itens_Venda(Itens_Venda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_Itens_Venda(Itens_Venda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_venda")]
	public partial class Vendas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venda;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<decimal> _desconto;
		
		private System.Nullable<decimal> _valor_pago;
		
		private System.Nullable<int> _Codigo_Pessoa_Venda;
		
		private EntitySet<Itens_Venda> _Itens_Venda;
		
		private EntitySet<Contas_Receber> _Contas_Receber;
		
		private EntityRef<Pessoas> _Pessoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void OnValor_vendaChanging(System.Nullable<decimal> value);
    partial void OnValor_vendaChanged();
    partial void OnDescontoChanging(System.Nullable<decimal> value);
    partial void OnDescontoChanged();
    partial void OnValor_pagoChanging(System.Nullable<decimal> value);
    partial void OnValor_pagoChanged();
    partial void OnCodigo_Pessoa_VendaChanging(System.Nullable<int> value);
    partial void OnCodigo_Pessoa_VendaChanged();
    #endregion
		
		public Vendas()
		{
			this._Itens_Venda = new EntitySet<Itens_Venda>(new Action<Itens_Venda>(this.attach_Itens_Venda), new Action<Itens_Venda>(this.detach_Itens_Venda));
			this._Contas_Receber = new EntitySet<Contas_Receber>(new Action<Contas_Receber>(this.attach_Contas_Receber), new Action<Contas_Receber>(this.detach_Contas_Receber));
			this._Pessoas = default(EntityRef<Pessoas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Valor_venda
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnValor_vendaChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("Valor_venda");
					this.OnValor_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desconto", Storage="_desconto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Desconto
		{
			get
			{
				return this._desconto;
			}
			set
			{
				if ((this._desconto != value))
				{
					this.OnDescontoChanging(value);
					this.SendPropertyChanging();
					this._desconto = value;
					this.SendPropertyChanged("Desconto");
					this.OnDescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor_pago", Storage="_valor_pago", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Valor_pago
		{
			get
			{
				return this._valor_pago;
			}
			set
			{
				if ((this._valor_pago != value))
				{
					this.OnValor_pagoChanging(value);
					this.SendPropertyChanging();
					this._valor_pago = value;
					this.SendPropertyChanged("Valor_pago");
					this.OnValor_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_Codigo_Pessoa_Venda", DbType="Int")]
		public System.Nullable<int> Codigo_Pessoa_Venda
		{
			get
			{
				return this._Codigo_Pessoa_Venda;
			}
			set
			{
				if ((this._Codigo_Pessoa_Venda != value))
				{
					this.OnCodigo_Pessoa_VendaChanging(value);
					this.SendPropertyChanging();
					this._Codigo_Pessoa_Venda = value;
					this.SendPropertyChanged("Codigo_Pessoa_Venda");
					this.OnCodigo_Pessoa_VendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendas_Itens_Venda", Storage="_Itens_Venda", ThisKey="id_venda", OtherKey="Codigo_venda")]
		public EntitySet<Itens_Venda> Itens_Venda
		{
			get
			{
				return this._Itens_Venda;
			}
			set
			{
				this._Itens_Venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendas_tb_contas_receber", Storage="_Contas_Receber", ThisKey="id_venda", OtherKey="Codigo_venda")]
		public EntitySet<Contas_Receber> Contas_Receber
		{
			get
			{
				return this._Contas_Receber;
			}
			set
			{
				this._Contas_Receber.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoas_Vendas", Storage="_Pessoas", ThisKey="Codigo_Pessoa_Venda", OtherKey="Codigo_pessoa", IsForeignKey=true)]
		public Pessoas Pessoas
		{
			get
			{
				return this._Pessoas.Entity;
			}
			set
			{
				Pessoas previousValue = this._Pessoas.Entity;
				if (((previousValue != value) 
							|| (this._Pessoas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pessoas.Entity = null;
						previousValue.Vendas.Remove(this);
					}
					this._Pessoas.Entity = value;
					if ((value != null))
					{
						value.Vendas.Add(this);
						this._Codigo_Pessoa_Venda = value.Codigo_pessoa;
					}
					else
					{
						this._Codigo_Pessoa_Venda = default(Nullable<int>);
					}
					this.SendPropertyChanged("Pessoas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Itens_Venda(Itens_Venda entity)
		{
			this.SendPropertyChanging();
			entity.Vendas = this;
		}
		
		private void detach_Itens_Venda(Itens_Venda entity)
		{
			this.SendPropertyChanging();
			entity.Vendas = null;
		}
		
		private void attach_Contas_Receber(Contas_Receber entity)
		{
			this.SendPropertyChanging();
			entity.Vendas = this;
		}
		
		private void detach_Contas_Receber(Contas_Receber entity)
		{
			this.SendPropertyChanging();
			entity.Vendas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoa")]
	public partial class Pessoas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo_pessoa;
		
		private string _Nome;
		
		private string _Telefone;
		
		private string _Email;
		
		private EntitySet<Vendas> _Vendas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigo_pessoaChanging(int value);
    partial void OnCodigo_pessoaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Pessoas()
		{
			this._Vendas = new EntitySet<Vendas>(new Action<Vendas>(this.attach_Vendas), new Action<Vendas>(this.detach_Vendas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_Codigo_pessoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo_pessoa
		{
			get
			{
				return this._Codigo_pessoa;
			}
			set
			{
				if ((this._Codigo_pessoa != value))
				{
					this.OnCodigo_pessoaChanging(value);
					this.SendPropertyChanging();
					this._Codigo_pessoa = value;
					this.SendPropertyChanged("Codigo_pessoa");
					this.OnCodigo_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome", Storage="_Nome", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="telefone", Storage="_Telefone", DbType="VarChar(30)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="email", Storage="_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoas_Vendas", Storage="_Vendas", ThisKey="Codigo_pessoa", OtherKey="Codigo_Pessoa_Venda")]
		public EntitySet<Vendas> Vendas
		{
			get
			{
				return this._Vendas;
			}
			set
			{
				this._Vendas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vendas(Vendas entity)
		{
			this.SendPropertyChanging();
			entity.Pessoas = this;
		}
		
		private void detach_Vendas(Vendas entity)
		{
			this.SendPropertyChanging();
			entity.Pessoas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_usuario")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _usuario;
		
		private string _senha;
		
		private int _id_pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void Onid_pessoaChanging(int value);
    partial void Onid_pessoaChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_venda")]
	public partial class Itens_Venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Quantidade;
		
		private int _Codigo_produto;
		
		private int _Codigo_venda;
		
		private decimal _Valor;
		
		private int _Codigo_item;
		
		private EntityRef<Produto> _Produto;
		
		private EntityRef<Vendas> _Vendas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuantidadeChanging(int value);
    partial void OnQuantidadeChanged();
    partial void OnCodigo_produtoChanging(int value);
    partial void OnCodigo_produtoChanged();
    partial void OnCodigo_vendaChanging(int value);
    partial void OnCodigo_vendaChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnCodigo_itemChanging(int value);
    partial void OnCodigo_itemChanged();
    #endregion
		
		public Itens_Venda()
		{
			this._Produto = default(EntityRef<Produto>);
			this._Vendas = default(EntityRef<Vendas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="quantidade", Storage="_Quantidade", DbType="Int NOT NULL")]
		public int Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_produto", Storage="_Codigo_produto", DbType="Int NOT NULL")]
		public int Codigo_produto
		{
			get
			{
				return this._Codigo_produto;
			}
			set
			{
				if ((this._Codigo_produto != value))
				{
					this.OnCodigo_produtoChanging(value);
					this.SendPropertyChanging();
					this._Codigo_produto = value;
					this.SendPropertyChanged("Codigo_produto");
					this.OnCodigo_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_Codigo_venda", DbType="Int NOT NULL")]
		public int Codigo_venda
		{
			get
			{
				return this._Codigo_venda;
			}
			set
			{
				if ((this._Codigo_venda != value))
				{
					this.OnCodigo_vendaChanging(value);
					this.SendPropertyChanging();
					this._Codigo_venda = value;
					this.SendPropertyChanged("Codigo_venda");
					this.OnCodigo_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_Valor", DbType="Decimal(15,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_item", Storage="_Codigo_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo_item
		{
			get
			{
				return this._Codigo_item;
			}
			set
			{
				if ((this._Codigo_item != value))
				{
					this.OnCodigo_itemChanging(value);
					this.SendPropertyChanging();
					this._Codigo_item = value;
					this.SendPropertyChanged("Codigo_item");
					this.OnCodigo_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Itens_Venda", Storage="_Produto", ThisKey="Codigo_produto", OtherKey="codigo", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.Itens_Venda.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.Itens_Venda.Add(this);
						this._Codigo_produto = value.codigo;
					}
					else
					{
						this._Codigo_produto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendas_Itens_Venda", Storage="_Vendas", ThisKey="Codigo_venda", OtherKey="id_venda", IsForeignKey=true)]
		public Vendas Vendas
		{
			get
			{
				return this._Vendas.Entity;
			}
			set
			{
				Vendas previousValue = this._Vendas.Entity;
				if (((previousValue != value) 
							|| (this._Vendas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vendas.Entity = null;
						previousValue.Itens_Venda.Remove(this);
					}
					this._Vendas.Entity = value;
					if ((value != null))
					{
						value.Itens_Venda.Add(this);
						this._Codigo_venda = value.id_venda;
					}
					else
					{
						this._Codigo_venda = default(int);
					}
					this.SendPropertyChanged("Vendas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_status_pagamento")]
	public partial class Status_Pagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _status;
		
		private EntitySet<Contas_Receber> _Contas_Receber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public Status_Pagamento()
		{
			this._Contas_Receber = new EntitySet<Contas_Receber>(new Action<Contas_Receber>(this.attach_Contas_Receber), new Action<Contas_Receber>(this.detach_Contas_Receber));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_pagamento_tb_contas_receber", Storage="_Contas_Receber", ThisKey="id_status", OtherKey="Codigo_status")]
		public EntitySet<Contas_Receber> Contas_Receber
		{
			get
			{
				return this._Contas_Receber;
			}
			set
			{
				this._Contas_Receber.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contas_Receber(Contas_Receber entity)
		{
			this.SendPropertyChanging();
			entity.Status_Pagamento = this;
		}
		
		private void detach_Contas_Receber(Contas_Receber entity)
		{
			this.SendPropertyChanging();
			entity.Status_Pagamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_contas_receber")]
	public partial class Contas_Receber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo_conta;
		
		private System.DateTime _Data_compra;
		
		private System.DateTime _Data_vencimento;
		
		private System.Nullable<System.DateTime> _Data_pagamento;
		
		private int _Codigo_venda;
		
		private int _Codigo_status;
		
		private EntityRef<Status_Pagamento> _Status_Pagamento;
		
		private EntityRef<Vendas> _Vendas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigo_contaChanging(int value);
    partial void OnCodigo_contaChanged();
    partial void OnData_compraChanging(System.DateTime value);
    partial void OnData_compraChanged();
    partial void OnData_vencimentoChanging(System.DateTime value);
    partial void OnData_vencimentoChanged();
    partial void OnData_pagamentoChanging(System.Nullable<System.DateTime> value);
    partial void OnData_pagamentoChanged();
    partial void OnCodigo_vendaChanging(int value);
    partial void OnCodigo_vendaChanged();
    partial void OnCodigo_statusChanging(int value);
    partial void OnCodigo_statusChanged();
    #endregion
		
		public Contas_Receber()
		{
			this._Status_Pagamento = default(EntityRef<Status_Pagamento>);
			this._Vendas = default(EntityRef<Vendas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_conta", Storage="_Codigo_conta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo_conta
		{
			get
			{
				return this._Codigo_conta;
			}
			set
			{
				if ((this._Codigo_conta != value))
				{
					this.OnCodigo_contaChanging(value);
					this.SendPropertyChanging();
					this._Codigo_conta = value;
					this.SendPropertyChanged("Codigo_conta");
					this.OnCodigo_contaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_compra", Storage="_Data_compra", DbType="Date NOT NULL")]
		public System.DateTime Data_compra
		{
			get
			{
				return this._Data_compra;
			}
			set
			{
				if ((this._Data_compra != value))
				{
					this.OnData_compraChanging(value);
					this.SendPropertyChanging();
					this._Data_compra = value;
					this.SendPropertyChanged("Data_compra");
					this.OnData_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_vencimento", Storage="_Data_vencimento", DbType="Date NOT NULL")]
		public System.DateTime Data_vencimento
		{
			get
			{
				return this._Data_vencimento;
			}
			set
			{
				if ((this._Data_vencimento != value))
				{
					this.OnData_vencimentoChanging(value);
					this.SendPropertyChanging();
					this._Data_vencimento = value;
					this.SendPropertyChanged("Data_vencimento");
					this.OnData_vencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_pagamento", Storage="_Data_pagamento", DbType="Date")]
		public System.Nullable<System.DateTime> Data_pagamento
		{
			get
			{
				return this._Data_pagamento;
			}
			set
			{
				if ((this._Data_pagamento != value))
				{
					this.OnData_pagamentoChanging(value);
					this.SendPropertyChanging();
					this._Data_pagamento = value;
					this.SendPropertyChanged("Data_pagamento");
					this.OnData_pagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_Codigo_venda", DbType="Int NOT NULL")]
		public int Codigo_venda
		{
			get
			{
				return this._Codigo_venda;
			}
			set
			{
				if ((this._Codigo_venda != value))
				{
					this.OnCodigo_vendaChanging(value);
					this.SendPropertyChanging();
					this._Codigo_venda = value;
					this.SendPropertyChanged("Codigo_venda");
					this.OnCodigo_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_Codigo_status", DbType="Int NOT NULL")]
		public int Codigo_status
		{
			get
			{
				return this._Codigo_status;
			}
			set
			{
				if ((this._Codigo_status != value))
				{
					this.OnCodigo_statusChanging(value);
					this.SendPropertyChanging();
					this._Codigo_status = value;
					this.SendPropertyChanged("Codigo_status");
					this.OnCodigo_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_pagamento_tb_contas_receber", Storage="_Status_Pagamento", ThisKey="Codigo_status", OtherKey="id_status", IsForeignKey=true)]
		public Status_Pagamento Status_Pagamento
		{
			get
			{
				return this._Status_Pagamento.Entity;
			}
			set
			{
				Status_Pagamento previousValue = this._Status_Pagamento.Entity;
				if (((previousValue != value) 
							|| (this._Status_Pagamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Status_Pagamento.Entity = null;
						previousValue.Contas_Receber.Remove(this);
					}
					this._Status_Pagamento.Entity = value;
					if ((value != null))
					{
						value.Contas_Receber.Add(this);
						this._Codigo_status = value.id_status;
					}
					else
					{
						this._Codigo_status = default(int);
					}
					this.SendPropertyChanged("Status_Pagamento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendas_tb_contas_receber", Storage="_Vendas", ThisKey="Codigo_venda", OtherKey="id_venda", IsForeignKey=true)]
		public Vendas Vendas
		{
			get
			{
				return this._Vendas.Entity;
			}
			set
			{
				Vendas previousValue = this._Vendas.Entity;
				if (((previousValue != value) 
							|| (this._Vendas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vendas.Entity = null;
						previousValue.Contas_Receber.Remove(this);
					}
					this._Vendas.Entity = value;
					if ((value != null))
					{
						value.Contas_Receber.Add(this);
						this._Codigo_venda = value.id_venda;
					}
					else
					{
						this._Codigo_venda = default(int);
					}
					this.SendPropertyChanged("Vendas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
